name: "Go Test"
description: "Run go tests"

inputs:
  pwd:
    description: Directory
    required: false

  name:
    description: Test run name
    required: false
    default: Tests

  packages:
    description: "Packages to run"
    required: false
    default: "./..."

  coverage:
    description: Calculate test coverage
    default: "false"

  token:
    description: github token
    default: ${{ secret.GITHUB_TOKEN }}

outputs:
  time: # id of output
    description: "The time we greeted you"

runs:
  using: "node16"
  main: "./lib/action.js"
