name: Pull Request
on: [pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "./example/go.mod"

      - name: Install gotestfmt
        run: go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest

      - name: Go test
        uses: ./ # Uses an action in the root directory
        with:
          name: Unit Tests
          pwd: ./example
          packages: ./...
          token: ${{ secrets.GITHUB_TOKEN }}

      # # Use the output from the `hello` step
      # - name: Get the output time
      #   run: echo "The time was ${{ steps.hello.outputs.time }}"
